server:
  port: 8081
  servlet:
    context-path: /virtual-trainer
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/trainer #Change it as per your local Database name
    username: root #Change it as per your local username
    password: admin  #Change it as per your local password
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 465
    username: sukumarm111@gmail.com
    password: zhimqbxideaswmgs
#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#            fallback: false
#            port: 465
#          auth: true
#          starttls:
#            enable: true


springdoc:
  swagger-ui:
    path: /virtual-trainer-swagger-ui.html
  api-docs:
    path: /v3/virtual-trainer-api-docs
